#!/bin/bash
gcc -std=c11 -o lang lang.c

runTest() {
    output=$(./lang "$1" | sed -e s/^M//)
    if [ "$output" != "$2" ]; then
      echo "$1: $2 expected, but got $output"
      exit 1
    fi
    echo "$1 => $output"
}

echo '=== basic ==='
runTest 0 0
runTest 1 1
runTest 99 99

runTest '1 2 3' '1
2
3'

echo '=== + ==='
runTest '+ 1 2' 3
runTest '+ 10 2' 12

echo '=== - ==='
runTest '- 2 1' 1
runTest '- 10 200' -190

echo OK
